### ISSUE TITLE
Getting MapScan to return string columns as is

### ISSUE THREAD

**Issue by u89012** [jmoiron/sqlx#116]
MapScan's awesome but it seems to return string columns as runes (if I'm not mistaken). Is there a way to have it just return strings as is instead?

Thanks for your awesome work on this library!

**Comment by jmoiron** [comment]
MapScan returns columns using the driver's default type for an `interface{}` destination.  Can you give me some information on what driver, value, and column type you were scanning using MapScan?

**Comment by u89012** [comment]
My apologies for lack of details, I'm using the following environment:

OS: Linux 3.13.0-43-generic
Go: 1.4 linux/amd64
DB: Postgres 9.4
Driver: libpq (github.com/lib/pq)
Column type: varchar(64)
Value expected: string
Value returned: array of numbers 

And here's how my code looks:

```
func rows(db *sqlx.DB, sql string, args...interface{})(a []map[string]interface{}){
    rows, err := db.Queryx(sql, args...)
    defer rows.Close()
    
    for rows.Next() {
        results := make(map[string]interface{})
        err = rows.MapScan(results)
        if err != nil {
            log.Fatalln(err)
        }
        a = append(a, results)
    }
    return
}
```


Please let me know if you need more details I may have missed.

**Comment by jmoiron** [comment]
The value of the return type was probably `[]byte` (not `[]rune`), which makes sense as that is what you will be reading out of a socket.  This is is convertible to a string via `string([]byte)`.  

Originally, I had used an `sql.NullString` as the default scan target, because I mistakenly thought all []byte coming in off the wire would at the very least scan correctly into it (most drivers support integer scanning to string destinations, eg).  Unfortunately, novel types like `time.Time` do not work for all drivers, so to fix this I had to resort to using an `interface{}` destination.

I'm afraid that it's up to the driver to make this conversion;  although I could do this in `sqlx` for []byte value types, this involves a copy and is therefore a costly decision that might not be what other people want.

In theory, it'd be nice to be able to MapScan into a `map[string]string`, but there is no way for the Go type system to cover that for me and I don't want to introduce more runtime type checking than necessary.  `MapScan` is something of a last resort; the preferred way of using sqlx is via StructScan, but since it's not always possible MapScan was written.

**Comment by u89012** [comment]
Thank you for the background on this. The type system is a bit lacking indeed and I agree not imposing the copy penalty on others who don't want it. Perhaps, the function could take a flag to determine so. I say this because at least in my usecase all columns just end up in some html template verbatim and would make similar use cases brain dead simple.

In other words, how about this? ```MapScan(m map[string]interface{}, convertBytesToString bool)```

That said, I can always typecast in my loop if you shoot it down.

**Comment by jmoiron** [comment]
I definitely can't change the API for that.  Instead, I'd have to add to it, something like:

```go
func MapScanString(m map[string]interface{})
```

In the end, It's a pretty simple function to perform the conversion in place.  I don't think it's a huge ask for people to write this if it's what they desire (and in fact, they might desire other manipulations on the []byte, like trimming it for whitespace):

```go
func mapBytesToString(m map[string]interface{}) {
    for k,v := range m {
        if b,ok := v.([]byte); ok {
            m[k] = string(b)
        }
    }
}
```

Thanks for the suggestion, but I think it's not worth increasing the surface area of the API for this.

**Comment by AndreKR** [comment]
For reference, this seems to be superseded by #80.
