### ISSUE TITLE
too many 'out' parameters

### ISSUE THREAD

**Issue by rickb777** [jmoiron/sqlx#121]
*sqlx* has an API strongly making use of 'out' parameters, i.e. mutables passed in that are mutated and the mutated state is used by the client.  Although Go allows this, it's not very idiomatic; return parameters can be much more flexible.

Too much dependence on 'out' parameters makes it hard to write code in a functional style. Even though Go is not a functional language, its idiom encourages writing functions and methods that returned values that can themselves be passed as input parameters, error checking permitting.

An example will illustrate this more:

    var count int
    err := db.Get(&count, "SELECT count(*) FROM person;")

a direct equivalent might be

    count, err := db.Get("SELECT count(*) FROM person;")

Of course, the challenge this presents is that the Get method needs to know how to type-convert the result row. In the *sqlx* case, passing in the `int` pointer gives a strong hint and makes type coercion easy. In the other style, it's not at all clear.  Using 'out' parameters is one way to solve this

Gorp, for comparison, "cheats" in this case by adding an extra method for `int`:

    count, err := dbmap.SelectInt("select count(*) from posts")

**Structs** 
The more interesting case is dealing with structs. In `sqlx`,

    people := []Person{}
    err := db.Select(&people, "SELECT * FROM person ORDER BY first_name ASC")

The only value returned is the error.  This is a shame; Gorp's style is to return the filled-in slice too, e.g. both of these work:

    var posts []Post
    posts, err := dbmap.Select(&posts, "select * from posts order by post_id")

    posts, err := dbmap.Select(&Post{}, "select * from posts order by post_id")

Clearly, in the second case Gorp has only used `&Post{}` for its type information, then creating, filling and returning the necessary slice for you. It's not that you *have* to use the return parameters.

But the lack of them in *sqlx* is limiting.

**Comment by kisielk** [comment]
Not sure how this is an issue, it's just a matter of a different design. What's the actionable thing here, to rewrite the package?

**Comment by jmoiron** [comment]
The standard library unmarshallers *all* use "out" parameters, *without exception*:

* [json](http://golang.org/pkg/encoding/json/#Unmarshal)
* [gob](http://golang.org/pkg/encoding/gob/#Decoder.Decode)
* [xml](http://golang.org/pkg/encoding/xml/#Decoder.Decode)

There are a few reasons this is done.  The interfaces for mutation must either return `interface{}` or mutate the receiver;  otherwise, there would be no way of implementing them across various types.   There is no exception here with `database/sql`, where you can [implement sql.Scanner](http://jmoiron.net/blog/built-in-interfaces).  Another is that unmarshalling is a memory intensive job and it's much more efficient to be able to allocate your unmarshalled representation up front;  you can do, eg:

```go
posts := make([]Post, 0, 10000)
err := db.Select(&posts, "SELECT * FROM post ORDER BY id DESC LIMIT 10000;")
```

And you will not have to suffer 10000 individual `Post{}` allocations.  And in situations where N is too many, I've still allowed the scanning behavior via the `Rows` object:

```go
var post Post{}
// select a million rows
rows, err := db.Queryx("SELECT * ...")
// handle err
for rows.Next() {
    rows.StructScan(&post)
    // do something with post, eg. post-aggregate
}
```

Even if out parameters did not have these advantages, your code becomes a complete mess of casts which you've not included.  Gorp's return values are all (by necessity, it can't know what types you want) `interface{}`, which means that even though the internal types match the type of the first parameter, they must be casted before use.  If you are returning an error along with it, you cannot cast directly off the function call.  Your example, for instance, doesn't work:

```go
var err error
var posts []Post
posts, err = db.Select(&Post{}, "...") // won't compile, Select returns interface{}
```

You must instead write code like this:

```go
iposts, err := db.Select(&Post{}, "...")
// check err
posts := iposts.([]Post)
```

In fact, I thought this behavior of Gorp's was so unidiomatic that I [forked it](http://github.com/jmoiron/modl) in order to remove it.  Gorp's own readme no longer features this API;  it sticks with the "out" parameter version.

Still, this mindset is why Gorp's API has things like `SelectInt`.  Personally, these feel rather limited to me.  You can use `sqlx.DB.Get` with *any* type, even custom ones that implement `db.Scanner`, and it comes at no added API noise.  What if you want to GetInt32?  or GetUint64?

I want to summarise here briefly by saying that:

* Go is not a functional language
* the way that sqlx approaches these parameters is consistent with the stdlib and therefore idiomatic
* this proposal is inconsistent with the stdlib and therefore *not* idiomatic.

I also want to thank you for your time and care in preparing this issue.  I really do appreciate it, even though I disagree with your opinions.  It is for this reason I've prepared such a long rebuttal.
