### ISSUE TITLE
Question about mapping

### ISSUE THREAD

**Issue by gravis** [jmoiron/sqlx#127]
Hi, 

I'm wondering how to fetch a struct with an embedded struct like:

```go
type User struct {
    ID uint64
    Name string
    Email string
}

type Team struct {
    ID uint64
    Owner User
}

 teams := []Team{}

 err := db.Select(&teams, `SELECT teams.id, owners.*  join teams on teams.user_id = users.id
         WHERE memberships.user_id = $1`, 1)
```

I'm getting an error `missing destination name`. The documentation is mentioning aliased, but I don't figure out what alias I could use. If I tag my user ID with `db:"user_id"`, I won't be able to use the `User` struct elsewhere. Any idea?

Thanks

**Comment by jmoiron** [comment]
Hi,

sqlx only supports extending attribute namespaces for embedded structs.  Eg:

```go
type Team struct {
    ID uint64
    User
}
```

**Comment by gravis** [comment]
Got it, thanks :)
So basically, I have to create a new temporary struct 

```
type TeamWithUser struct {
    ID uint64
    User
}```

or raw scan? 

Any plan to support fully embedded structs?

**Comment by jszwedko** [comment]
@gravis That is just adding a field with type `User` to the struct, not embedding the struct. See https://golang.org/doc/effective_go.html#embedding

I don't really have an opinion on whether or not `sqlx` should handle "flattening" the fields though.

**Comment by jmoiron** [comment]
It used to "flatten" fields.  It become sort of complicated, because there are a lot of structs that people do not *think* of as structs, like `time.Time` or `sql.NullString`.  Embedding a struct is a much stronger hint that its attributes should belong to the outer one.  Requiring it to be embedded brings it in line with Go's access rules and, once you sort of understand those, it becomes easier to reason about.
