### ISSUE TITLE
MapScan and SliceScan string conversion pain point

### ISSUE THREAD

**Issue by johnleegrant** [jmoiron/sqlx#135]
In the same way Get and Select semantics have been introduced for Scan and StructScan, I'm wondering if something similar could be added for MapScan and SliceScan. It's so useful to be able to go from a SQL statement to JSON via MapScan - example use case would be dynamic pivot queries. I find I need to use the following code to make the sqlx alternate scan types useful - MapBytesToString is necessary to prevent json.Marshal from returning Base64 instead of strings. This doesn't feel right to me. There must be a more, erm, idiomatic way to achieve this and may be it could be included as part of the core sqlx package?

```go
package sqlxx

import "github.com/jmoiron/sqlx"

func MapBytesToString(m map[string]interface{}) {
	for k, v := range m {
		if b, ok := v.([]byte); ok {
			m[k] = string(b)
		}
	}
}

func MapScan(r sqlx.ColScanner, dest map[string]interface{}) error {
	err := sqlx.MapScan(r, dest)
	if err != nil {
		return err
	}
	MapBytesToString(dest)
	return nil
}

func SliceBytesToString(s []interface{}) {
	for k, v := range s {
		if b, ok := v.([]byte); ok {
			s[k] = string(b)
		}
	}
}

func MapSlice(r sqlx.ColScanner) ([]interface{}, error) {
	s , err := sqlx.SliceScan(r)
	if err != nil {
		return nil, err
	}
	SliceBytesToString(s)
	return s, nil
}
```

**Comment by jmoiron** [comment]
For a little history, this used to scan directly to the `sql.NullString` type and use `string` if Valid was true, but I got a bug report saying that `lib/pq` refused to scan `time.Time` into a string.  I realized that my only reliable choice was to use `interface{}`.  There are two problems with this proposal:

* it's subtle, potentially breaking behavior
* not all `[]byte` are valid `string`

I am actually okay with 1 if it weren't for 2, but that makes this incredibly unlikely.  If you are scanning `bytea` type in PostgreSQL with SliceScan, some may be `[]byte` and some `string`, depending on their *contents*.  I think this is unacceptable behavior.  If you have heterogeneous data you're scanning into a `[]interface{}`, then only *your* app will know how to properly deal with that;  there isn't a decision sqlx can make that will work.  It's at this point that I recommend using a `struct`.

I would rather sqlx be 100% reliable and do something slightly inconvenient 90% of the time than be 90% convenient and 10% unreliable.

Still, I know that `MapScan` and `SliceScan` can be frustrating to people, and that you cannot always define structs for all your SQL result sets.  You're [not the first one](https://github.com/jmoiron/sqlx/issues/80#issuecomment-76088110) to say that the usefulness of MapScan and SliceScan is reduced because of this.  I suspect the half-way for many people will be to change `SliceScan` to use outparams and to finally fix #80.  

This would mean that you could pass `map[string]string` to MapScan and `[]string` to SliceScan, and deal with the fallout of that as you need to, even from sql eg, many people complain about NULL but you can use COALESCE to ensure empty string instead of NULL if that's actually a valid thing to do for your data model.

**Comment by jmoiron** [comment]
Yeah I apologize, my assertions above about strings and bytes are [not right](http://play.golang.org/p/HVQsxjz7QE).  It may make sense to coerce anything that ended up as a []byte to a string in map & slice scan, though if they accept out params that will have to be changed to only kick in if the argument value type was actually `interface{}`.

**Comment by johnleegrant** [comment]
Fair enough. I can't argue with that. Please feel free to close the issue.

I'd like to leave with a positive thought. I need to give this idea some more thought and it may be best served as some kind of sqlx extension or contrib.

The sqlx package is an excellent time saver and occupies space between the standard library and a full-blown ORM. You've added great new semantics: Get() and Select(). Adding GetJSON() to the toolbox is probably just what I'm looking for.

The reason I think this could work is by looking at it from the limitations of the JSON format. JSON only supports a small number of data types: string, number, object, array, true, false and null.

As you've pointed out, scanning a bytea is tricky and there will be plenty more unusual data types to contend with. On the other hand, I can't see why anyone would attempt to encode such data types to JSON. I think I'd be happy for a GetJSON implementation to default to string or even ignore exotic data types.

GetJSON would therefore involve caveats but would be really handy, more so if it could be battle-hardened as part of sqlx.

Thank you again for your considered response. Moreover, thank you for sharing sqlx.

**Comment by johnleegrant** [comment]
I know it's a cop-out but for dynamic queries, like reports, I’m making good progress using the quick and convenient JSON functions in PostgreSQL 9+:
```SQL
SELECT json_agg(t) AS results
FROM (VALUES (1.2, 2.7), (3.2, 4.1), (3.0, 4.4)) AS t(x, y);
```
For things like AJAX calls, it does seem a wasted effort to obtain strongly typed results in Go only to marshal them to JSON.
