### ISSUE TITLE
[Feature Request] Prefix Tables

### ISSUE THREAD

**Issue by mewben** [jmoiron/sqlx#141]
I wonder if it will be possible to globally prefix table names like this:

`var tbl_prefix = "go_"`

and in a query like this:
```
cityState := `INSERT INTO place (country, telcode) VALUES (?, ?)`
```

it automatically points to `go_place` table.

Maybe this is much of work to do. I was just thinking maybe... :)

**Comment by jmoiron** [comment]
You'd have to parse the query to achieve this, and since it's not quite so straight forward as query params (`?`) or named params (`:foo`), it'd probably *actually* have to parse the SQL and make some sense of it to discover table names.  For instance, you'd have to support your sample, but also queries like:

```sql
SELECT (president, telcode) FROM presidents INNER JOIN place ON presidents.place_id = place.id;
```

Finding the table name in there is difficult, and sqlx doesn't know what to look for because it doesn't have any knowledge of your schema.  Sorry, but I don't think this fits with the rest of sqlx;  it's too sophisticated to be done reliably.

Thanks for the suggestion!

**Comment by mewben** [comment]
yah.. I thought so. very complex. Thank you very much for the quick reply owner sir... Very cool library by the way. Cheers!
