### ISSUE TITLE
Apply mapper function to SQL column names

### ISSUE THREAD

**Issue by danielalves** [jmoiron/sqlx#142]
Since sqlx does not apply the mapper function to SQL column names, the code below results in an error `missing destination name Simple`:
```go
type Foo struct {
  Simple int
  CamelCased int
}

var bar Foo
db.Get(&bar, "SELECT Simple, CamelCased FROM Table WHERE Id = ?", anId)
```

This occurs because the default behavior of sqlx is to apply `strings.ToLower` to field names. Shouldn't it better if we applied the same mapper function to SQL column names? This way we would not need to worry about writing SQL column names with the same case as the transformed field names. This becomes even more evident with CamelCased column names. To make it work, the query becomes harder to read:
```go
var bar Foo
db.Get(&bar, "SELECT simple, camelcased FROM Table WHERE Id = ?", anId)
```

Was this considered before? Aborted for performance reasons? Of course I could set a "do nothing" mapper function up, but it is tedious to do that on every project/db connection.

**Comment by jmoiron** [comment]
MapperFuncs in general are something that I kind of regret.  Other stdlib marshallers are case insensitive and that might have made good sense for sqlx as well.

Despite this, setting a noop mapper func is:

```go
db := sqlx.Connect(...)
db.MapperFunc(func(s string) string { return s })
```

Which I'd hardly call tedious.  You generally only connect to any particular database once per project, and sqlx has a (deprecated but still usable) global mapper you can also set.

As for your suggestion, altering normal SQL queries is very difficult.  As I explained in #141 identifying things like columns or tables is often non-trivial (there are aliases, aggregation functions, etc) and would require parsing SQL.  It would result in some weird edge cases for many people.  I'd rather provide something that does 50% of what you need perfectly than 90% of what you need with weird edge conditions that bite you.  As such, `sqlx` only parses queries for two reasons at the moment, and both parsers are intentionally incredibly straight forward and easy to reason about:

* named queries consider any `:` prefixed string inside a query to be a named parameter
* query rebinding considers any `?` to be a bindVar

These are okay because rebinding and named queries are opt-in and the documentation covers these caveats.  If you end up needing a literal "?" in your query, you can skip sqlx's rebinding and write the queries manually for the backends you need (or implement your own escaping rebind function).  If you need to use `:foo` in your query, you'll just have to live without named queries.  These are acceptable tradeoffs to make the behavior simple and straightforward.

Given that:

* parsing sql is very complex, error prone, a security issue, etc
* sqlx already avoids it in nearly all cases
* the workaround for this is already provided with a single line by other means

I don't think that this will be doable.

Thank you for your suggestion!  I hope I was able to convince you that it is either undesirable or at least too complex to function adequately without lots of work.

**Comment by danielalves** [comment]
@jmoiron Yes, you did! Thanks for the fast response :+1:
