### ISSUE TITLE
PR #140 is not backwards-compatible

### ISSUE THREAD

**Issue by aronatkins** [jmoiron/sqlx#158]
I had a struct like:

```
type FooRecord struct {
  Id int64 `db:"id"`
  OtherId int64 `db:"other"`
  Other *Other
}
```

Note that the `Other` field did not have a `db` struct tag. It is optionally populated downstream (using the value of `OtherId`, but that's immaterial.

Prior to PR #140, this properly mapped queries like:

```
INSERT INTO foo (other) VALUES (:other)
```

After PR #140, the `other` column is being mapped to the `Other` field and not `OtherId`.

My workaround is to add an empty `db:""` tag to the `Other` field.

**Comment by jmoiron** [comment]
If you want to skip you can use the `db:"-"` tag.  I will look into the impact of that PR.  Thanks for the report!

**Comment by aronatkins** [comment]
Ah. Thanks. the `db:""` worked, but I'll shift to `db:"-"`.

It feels like the mapping that I had was always ambiguous, so I can understand the breakage. Not sure how common it might be.

**Comment by jmoiron** [comment]
Yeah, at some point non-embedded structs stopped contributing their fields to the mapping for their containing structs, because that was complicated to get right (eg. it broke scanning `time.Time`). 

I'll try to get a full grasp on how the behavior changed so I can at least document that it has done and provide a git tag for people who can't change things as easily.

**Comment by jmoiron** [comment]
It would be possible for the mapping that is build from the struct tree to give precedence to something with the `db` tag (or whatever tag you've chosen), but I think that's actually too complicated.  Go struct field order has real significance in a number of ways (eg its layout in memory and the order of fields in the reflect package), and given the ability to control the destination name with the db tag I think a simple "last one wins" is a simple enough rule that shouldn't limit anyone;  the only way you can get there is by giving a tag to a field that is identical to what another one would get, which is a bit of an ambiguous situation anyway.

I'm doing an audit now of how the naming works in detail so that some kind of easily understandable spec can be written, as I also have to find and fix an infinite recursion bug for type trees that have cycles in them.
