### ISSUE TITLE
could not find name  in map[string]interface {}

### ISSUE THREAD

**Issue by alexanderbaran** [jmoiron/sqlx#169]
I keep getting this error when using NamedQuery()

I get it in several places in the code. Here is an example of the issue:

http://stackoverflow.com/questions/32614019/sqlx-error-could-not-find-name-in-mapstringinterface-userid10

**Comment by alexanderbaran** [comment]
UploadURL = "http://localhost:8080/assets/upload"

It crashes with the url.

**Comment by jmoiron** [comment]
Hello, can you please provide your code here. The stack overflow question is gone now.

**Comment by jmoiron** [comment]
Closing this issue as the original stack overflow question is gone and there's nothing to go on.  @alexanderbaran feel free to reopen if you still are having problems and can provide example code in this issue.

**Comment by feliksik** [comment]
This issue is still relevant at commit d9bd385 . 

The problem occurs in any names statement that you attempt to prepare, when there is a ':' in there, that is not intended as a name. This is the case when you have a comment, or a literal string. 


```
-- this query will go wrong: << there is a colon here
SELECT 
  field1, 
  CONCAT("title: ", field2) as titelized -- this will go wrong, too!
 from table 
```

I would suggest: 
1) SIMPLE: quote the name, so it prints: "could not find name '' in ...". 

```
named.go
169:			return arglist, fmt.Errorf("could not find name %s in %#v", names[i], arg)
185:			return arglist, fmt.Errorf("could not find name %s in %#v", name, arg)

change to: 
```

2) SIMPLE: append additional warning if the name is empty string

3) OPTIONAL/ADVANCED: more advanced parsing -- but I guess this is out of scope.

**Comment by aprice2704** [comment]
I just ran into this also. I could use something other than a colon.

**Comment by aprice2704** [comment]
Nope, I guess that wasn't it after all. Changed to ., still having problems :( Back to positional.

**Comment by rawlinp** [comment]
I just ran into this too. If your query contains a literal `:`, it needs to be escaped with `::`. See #91.

**Comment by fwielstra** [comment]
I just ran into this with an SQL query that had a URL in a comment, e.g.

```sql
-- https://github.com/jmoiron/sqlx/issues/169
SELECT 'foo';
```

I have this use case because I prefer to keep my SQL queries in dedicated .sql files (embedded into my binary), so that I can run them separately from my application (e.g. from my IDE).

I guess that the parser should either ignore comments, or use a more advanced AST that only pulls things through the replacer where named replacement variables are relevant.

**Comment by izolate** [comment]
I ran into this as well, with a TODO comment in the SQL query:

```sql
SELECT * FROM example
WHERE some = 'thing';
-- TODO: order by clause
```

Gives the error:
```
could not find name  in map[string]interface{}{...}
```

**Comment by clarkmcc** [comment]
Ran into this because of

```sql
strftime('%Y-%m-%d %H:%M:00', start_timestamp)
```

Seems like this should be supported...
