### ISSUE TITLE
tx.Stmtx(stmt) type switch has no default

### ISSUE THREAD

**Issue by backerman** [jmoiron/sqlx#182]
Passing the wrong parameter (which isn't a prepared statement) to this function results in a null-dereference panic when the return value is called—should probably have a default case that panics if the parameter isn't of type sql(x)?.Stmt.

**Comment by jmoiron** [comment]
The delayed panic isn't great because it masks where the real issue occured.  There are two changes I could make here:

1. panic right away if a non-Stmt (either sql or sqlx style) is passed to `tx.Stmtx`
2. use a Stmt-ish interface to prevent something completely nonsensical from passing compilation

I do think this is a panic-able offence, so I'm fine with adding 1 regardless to address this particular issue.  

2 is technically a breaking change, but it would be unlikely to break any currently functioning code;  the only thing I can think of is passing an explicitly created `interface{}` value for a Stmt here.  I try pretty hard not to break peoples code but if I have to to improve the library I prefer it to either work 100% compatibly or issue a trivial compiler error.

**Comment by jmoiron** [comment]
I'm going to leave off the 2nd bit of this for now.  Not convinced its necessary, and the panic now has a better message and happens at the site of the issue.
