### ISSUE TITLE
Inconsistent behavior in work with NULL / pointer field on SELECT / INSERT

### ISSUE THREAD

**Issue by zamotivator** [jmoiron/sqlx#213]
Here is test-case with problem descriptions and expected behavior
https://gist.github.com/zamotivator/eee125e05dd123f69b6b

**Comment by jmoiron** [comment]
I've tried to read what is going on here..  some words like "value" and "pointer" are _very_ overloaded in the test source, so I'll try to specify a bit more.

The first `PROBLEM` line is panicking because the `ValueByValue` type (I'll call it `VBV`) [does not implement Value on a pointer receiver](https://gist.github.com/zamotivator/eee125e05dd123f69b6b#file-gistfile1-txt-L38-L40), so Go is forced to deref the method receiver in order to call it with a copy, and cannot since the receiver doesn't exist.  Read [this faq section](https://golang.org/doc/faq#methods_on_values_or_pointers) for more details on the difference.

The second `PROBLEM` fails because `c.Field` is a `ValueByPointer` struct, and an unaddressable copy of `c.Field` does not implement `Value()`, which is only implemented on the pointer method.  This is a side effect of the machinery of `NamedExec`;  I'm not sure it makes sense for NamedExec to attempt to create references or dereferences parts of the struct that are passed in;  it's unusual to implement Valuer on a non-value type.

The last issue is simply that `sql.NullString` is not a valid `driver.Value`, which is [restricted to a set of types](https://golang.org/pkg/database/sql/driver/#Value).  Your workaround patches are simply inserting the `sql.NullString` into the arg list (rather than your type), which does implement its `Value()` function correctly and return only the required types.

Some of the nuances here are confusing, I don't think there's anything actionable here.  If you have any other questions please let me know!
