### ISSUE TITLE
Get does not show correct error

### ISSUE THREAD

**Issue by blockloop** [jmoiron/sqlx#237]
``` Go
func CreateLeadAddress(a Address) (*int, error) {
    stmt, err := db.PrepareNamed(`EXEC crud.addressCreate
        @LeadId  = :LeadId
        @AddressTypeId  = :AddressTypeId
        // ... other fields
        `)

    if err != nil {
        return nil, errors.Wrap(err, "data: could not create address")
    }

    var newID int

    // VERSION 1
    if err := stmt.Get(&newID, &a); err != nil {
        return nil, errors.Wrap(err, "data: could not create address")
    }
    // END VERSION 1

    // VERSION 2
    if _, err := stmt.Exec(&a); err != nil {
        return nil, errors.Wrap(err, "data: could not create address")
    }
    // END VERSION 2

    return &newID, nil
}
```

In the above code, Version 2 will raise an error `mssql: Cannot insert the value NULL into column 'AddressTypeId', table 'Opportunity.dbo.OpportunityAddress'; column does not allow nulls. INSERT fails.`

Version 1 will fail trying to Scan and show `sql: Scan error on column index 0: converting driver.Value type <nil> ("<nil>") to a int: invalid syntax`. I'm not sure if this is a golang database/sql issue or perhaps I'm doing something wrong, but I expect the error from `Exec` to be shown if I call `Get` on the same statement.

**Comment by jmoiron** [comment]
Hi @blockloop,

It certainly looks like a bug.  If query execution fails I expect to see the query execution failure rather than a scan failure.  It leads me to believe that perhaps something else isn't working.

However, I tried (and failed) to create this issue here: https://github.com/jmoiron/sqlx/commit/27c2eb278029ef75df0477d9348d9e7922c63964

It features a column that is not nullable, a named insertion statement that should fail because of that constraint and that returns a value, and a print statement for each error encountered.  Running tests on this branch gets me:

```
20:20:27 jmoiron@sanji:$GOPATH/src/github.com/jmoiron/sqlx (master *)$ go test
pq: null value in column "added_at" violates not-null constraint
pq: null value in column "added_at" violates not-null constraint
PASS
ok  	github.com/jmoiron/sqlx	3.600s
```

Do you think you could replicate this error in the sqlx test suite?  I didn't get around to creating a stored procedure for it, i'm not exactly sure what the other parameters of this bug are.

**Comment by blockloop** [comment]
I'll try this evening

**Comment by blockloop** [comment]
Cleaning up old PRs. Closing this as stale and old.
