### ISSUE TITLE
Add NamedQueryRow() method

### ISSUE THREAD

**Issue by koorgoo** [jmoiron/sqlx#256]
My database is PostgreSQL. It does not support `sql.Result.LastInsertId()`, thus I am forced to use `RETURNING <fields>` construction to know ids of new records.

Now I use `sqlx.NamedStmt` to profit from named query and single struct result:

```go
type User struct {
  Name, Email string
}

func Create(db *sqlx.DB, user *User) error {
  stmt, err := db.PrepareNamed(`
  INSERT INTO users(name, email)
  VALUES(:name, :email) RETURNING id`)
  if err != nil {
    return err
  }
  defer stmt.Close()
  return stmt.Get(user, user)
}
```

`NamedQueryRow()` will allow to write cleaner code:

```go
func Create(db *sqlx.DB, user *User) error {
  return db.NamedQueryRow(`
  INSERT INTO users(name, email)
  VALUES(:name, :email) RETURNING id`, user).ScanStruct(user)
}
```

Method must be added to `*sqlx.DB` and `*sqlx.Tx`.

**Comment by jmoiron** [comment]
I don't want to add any more to the API (which is about to grow a lot with the addition of context to the database package), and it's easy to write functions that do this if you need them.

**Comment by alexandrevicenzi** [comment]
@jmoiron no way to add NamedQueryRow? There are 3 closed issues requesting the same thing, so it would be good to maybe think about it.

I would open an issue too, but there's no need since there are others issues requesting the same thing.

This is a feature that I would like to see along with the fix for ambiguous column names that I think there's no way to fix without using an 'AS' to rename the column.

**Comment by lpar** [comment]
Found myself here because I was wondering if anyone had asked for `NamedQueryRowContext` yet, so I can understand why there's no desire to open this particular can of worms.
