### ISSUE TITLE
sqlx 查询没有记录时，不应该返回 error

### ISSUE THREAD

**Issue by panjunjie** [jmoiron/sqlx#323]
sqlx 查询没有记录时，不应该返回 error；我觉得没有记录和执行错误是两个概念，但是 sqlx 把这两个东西混在一起了，对我们开发来说，有点不方便，我们很难分辨哪些是没有记录，哪些是错误的。

**Comment by hyfrey** [comment]
Please use English, there are a lot of people don't speak Chinese.

For your question, you can use  `err == sqlx.ErrNoRows` to determine the result is empty rather than other error. If the API does't return error, how can you know the result is empty, you can't compare returned value to default value since there are values equal default value.

**Comment by panjunjie** [comment]
it has been solved. thank you! I will close it.
