### ISSUE TITLE
NamedQuery() vs Queryx() have different parsing of colons

### ISSUE THREAD

**Issue by watercraft** [jmoiron/sqlx#452]
NamedQuery() will allow me to escape colons with the double colon ('::') but passing the same string to Queryx() doesn't and passes the double colon through.  This is a problem when I use the same application logic to build the query. My current workaround is to always call NamedQuery() and pass an empty map, e.g. NamedQuery(query, make(map[string]interface{}))

**Comment by jmoiron** [comment]
This is by design.  Typically, you cannot use the same query with Queryx and NamedQuery because Queryx will not utilize the named query vars correctly.  The exception to this is Oracle and any other dbs that use the NamedQuery syntax as their native bindvars.  If you're using such a db, then you should just use Queryx/Query and avoid NamedQuery.
