### ISSUE TITLE
Get() scanning to protobuf.timestamp

### ISSUE THREAD

**Issue by m-fagan** [jmoiron/sqlx#502]
I am using protocol buffer and serialize/deserialize protocol message struct to mysql database.
```
message ProtoStruct {
  string name = 1;
  ...
  google.protobuf.Timestamp reminder = 5;
}
```

Table column in mysql is TIMESTAMP.
I can insert/read mysql TIMESTAMP column using ptypes helper functions.
```
var reminder time.Time
	if err := rows.Scan(&td.Id, &td.Title, &td.Description, &reminder); err != nil {
		return nil, status.Error(codes.Unknown, "fail")
	}
	protoStruct.Reminder, err = ptypes.TimestampProto(reminder)
```
[link](https://medium.com/@amsokol.com/tutorial-how-to-develop-go-grpc-microservice-with-http-rest-endpoint-middleware-kubernetes-daebb36a97e9)

Since this requires manual marshaling, I want to use sqlx to handle them.

How can I do this?
Is there any way that I can inject time.Time <> protobuf.Timestamp func in sqlx?

**Comment by jmoiron** [comment]
You cannot directly use a timestamp if you don't own that type;  this is due to the way that `database/sql` allows you to control scanning.  You can, however, write your own wrapper type which implements `driver.Valuer` and `driver.Scanner`.  This is covered briefly [in the docs](http://jmoiron.github.io/sqlx/#customTypes).
