### ISSUE TITLE
empty slice passed to 'in' query

### ISSUE THREAD

**Issue by carr123** [jmoiron/sqlx#582]
arr := []int{}
query, args, err := sqlx.In("SELECT * FROM users WHERE level  NOT IN (?);", arr)
if err != nil{
fmt.Println(err)
}

some times, i really pass in a empty array to search data.
could you treat empty array as normal input instead of an error ?

**Comment by mkilpatrick** [comment]
What are you looking to happen in the case you pass an empty slice? Would you get all results returned or none? 

If none I'd argue that you should just check if your slice is empty and return no results, rather than leaving it up to the db anyways. Why perform an operation when there will never be a result? Just short circuit.

In the case that you want all results returned, you should condition it so you have a separate query if your slice is empty.

In my opinion, I don't think the current functionality should change.

**Comment by carr123** [comment]
thanks

**Comment by triadmoko** [comment]
```golang
count := 0
	err = r.getInCtx(ctx, &count, queryCount+where, args...)
	if err != nil {
		return nil, 0, err
	}
```
**args...**

**Comment by walles** [comment]
TIL empty `IN ()` clauses are not valid SQL.

Is this why `sqlx` can't support this?

From: https://github.com/jmoiron/sqlx/issues/196#issuecomment-167601496

> * mentions that `IN ()` is [not valid syntax](http://sqlfiddle.com/#!2/a2581/2411)
