### ISSUE TITLE
why sqlx Row type does not have Close() error method?

### ISSUE THREAD

**Issue by vtolstov** [jmoiron/sqlx#641]
I'm check sqlx code for QueryRowxContext internally it run database/sql QueryContext method that returns sql.Rows type that have Close() error method. So i can free memory by calling Close on result. But in sqlx i cant do that when func returns Row and not Rows type.

**Comment by vtolstov** [comment]
mostly this can leak connections

**Comment by methane** [comment]
See https://golang.org/pkg/database/sql/#Conn.QueryRowContext. It returns Row, not Rows. It doesn't leak connection.

**Comment by vtolstov** [comment]
please, re-read my words. https://github.com/jmoiron/sqlx/blob/v1.2.0/sqlx_context.go#L170 it uses NOT QueryRowContext but QueryContext that returns Rows. So fix for sqlx is needed to not leak connections. May be using proper function from database/sql package

**Comment by methane** [comment]
Oh, I'm sorry.
Anyway, it closes the underlaying sql.Rows.
https://github.com/jmoiron/sqlx/blob/0794cb1f47ee444eda9624f952ab8a370bec22de/sqlx.go#L198

**Comment by vtolstov** [comment]
yes, but if you not doing Scan it does not. I'm not fully dig into sqlx but in my app when i'm use function connections leaked

**Comment by nussjustin** [comment]
The behavior is the same as for the `(*Row).Scan` method in the `database/sql` package. In fact, the `database/sql.Row` also [wraps](https://golang.org/src/database/sql/sql.go?s=91886:91931#L3186) a `database/sql.Rows` instance.

What are you using the `Row` for if you are not calling `Scan`? Other than calling `Scan` there is only `Columns` and `ColumnTypes` (ignoring `Err` which doesn't make much sense unless `Scan` was called).

Even if you could close the `Row` without calling `Scan` that would be quite inefficient since the DB connection can't be reused in this case (`sqlx` could try to read all the rows internally, but that can lead to other problems)

**Comment by vtolstov** [comment]
Thanks
