### ISSUE TITLE
Is this repo still actively maintained?

### ISSUE THREAD

**Issue by romandvoskin** [jmoiron/sqlx#678]
I have a PR open that addresses 3 issues but no one has reviewed or commented on it. The last commit to `master` is Nov 20, 2020. We have production software dependent on this repo. If it's no longer actively maintained it would be helpful to know.

Reference: https://github.com/jmoiron/sqlx/pull/667

**Comment by jseteny** [comment]
We are at [Bitrise](https://www.bitrise.io) evaluating the possible replacements for gobuffalo/pop on the following week. So far my choice would be sqlx, but would like to be sure, that it is actively developed. Please reply my comment.

**Comment by romandvoskin** [comment]
It looks like gobuffalo/pop also uses sqlx https://github.com/gobuffalo/pop/blob/master/go.mod#L25

**Comment by connorjcantrell** [comment]
@romandvoskin have you found any good alternatives to sqlx?

**Comment by xNevo** [comment]
@romandvoskin Please see https://www.reddit.com/r/golang/comments/l43wn7/what_happened_to_sqlx/

**Comment by jmoiron** [comment]
I'll briefly expand upon what's in the linked post.

The library is maintained.  

It is actively used in a large private repos with hundreds of developers.  I am pretty responsive to issues we encounter, but sadly I have not been as responsive to the community.   Like an email that you will "reply to later", your delay eventually compounds and becomes a barrier to engagement in and of itself. 

This project predates go modules by several years, and because of that I've not been attentive enough to that workflow.  

I'm going to be addressing that going forward, and tagging more changes.

I've gone through and merged or closed about half of the outstanding PRs as part of the newly tagged 1.3.0, and I'm hoping to pare down the issue list as well.

**Comment by connorjcantrell** [comment]
@jmoiron Thank you for the update. I can only imagine the weight that comes with maintaining something like sqlx. If you are interested in bringing on contributors, I may be interested. 

Thanks for your hard work,
Connor
